### PR TITLE
Add synclogfact dag

### PR DESCRIPTION
**Pull request by sravfeyn**

### CODE REVIEW

**Comment by sravfeyn** [comment]
@calellowitz @gcapalbo

**Comment by gcapalbo** [comment]
looks good to me, @calellowitz i think this requires changes based on your latest changes to https://github.com/dimagi/pipes/pull/2 is that right?

**Comment by calellowitz** [comment]
@gcapalbo I do not believe so, what changes are you referring to

**Comment by gcapalbo** [comment]
@calellowitz nevermind, i misread

**Pull request merged**
